rest:
  security:
    issuer-uri: ${AUTH_SERVER_URI:http://localhost:8080/auth/realms/dev}
    api-matcher: /**
    cors:
      allowed-origins: '*'
      allowed-headers: '*'
      allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
      max-age: 3600

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${rest.security.issuer-uri}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: framework
          predicates:
            - Path=/services/rest/{application}/{version}/**
          uri: lb://application-version
          filters:
            - StripPrefix=4
            - UriHostPlaceholderFilter
#logging:
#  level:
#    org:
#      springframework:
#        web: TRACE