server:
  port: 8082

rest:
  security:
    issuer-uri: http://localhost:8080/auth/realms/dev
    api-matcher: /**
    cors:
      allowed-origins: '*'
      allowed-headers: '*'
      allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
      max-age: 3600

spring:
  application:
    name: gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${rest.security.issuer-uri}

  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}
        healthCheckPath: /health-check
        healthCheckInterval: 20s
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: framework
          predicates:
            - Path=/{application}/**
          uri: lb://application
          filters:
            - StripPrefix=1
            - UriHostPlaceholderFilter
#logging:
#  level:
#    org:
#      springframework:
#        web: TRACE